# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech64_10.1c/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/V_project/IP/ad_fft/tmp_edit_project.cache/wt [current_project]
set_property parent.project_path D:/FPGA/V_project/IP/ad_fft/tmp_edit_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip D:/FPGA/V_project/IP/ad_fft/src/xfft_2/xfft_2.xci
set_property is_locked true [get_files D:/FPGA/V_project/IP/ad_fft/src/xfft_2/xfft_2.xci]

read_ip D:/FPGA/V_project/IP/ad_fft/src/xfft_1/xfft_1.xci
set_property is_locked true [get_files D:/FPGA/V_project/IP/ad_fft/src/xfft_1/xfft_1.xci]

read_verilog -library xil_defaultlib {
  D:/FPGA/V_project/IP/ad_fft/src/ad2.v
  D:/FPGA/V_project/IP/ad_fft/src/ad1.v
  D:/FPGA/V_project/IP/ad_fft/src/fft1.v
  D:/FPGA/V_project/IP/ad_fft/src/fft2.v
  D:/FPGA/V_project/IP/ad_fft/src/ad14.v
  D:/FPGA/V_project/IP/ad_fft/src/fft14.v
  D:/FPGA/V_project/IP/ad_fft/src/ad_fft.v
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ad_fft -part xc7z020clg400-2
write_checkpoint -noxdef ad_fft.dcp
catch { report_utilization -file ad_fft_utilization_synth.rpt -pb ad_fft_utilization_synth.pb }
