# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/V_project/IP/ad_fft/src/xfft_2/xfft_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_2 || ORIG_REF_NAME==xfft_2}]

# IP: D:/FPGA/V_project/IP/ad_fft/src/xfft_1/xfft_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xfft_1 || ORIG_REF_NAME==xfft_1}]
