# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech64_10.1c/win64
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/V_project/final_2/lcd7_touch.cache/wt [current_project]
set_property parent.project_path D:/FPGA/V_project/final_2/lcd7_touch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/FPGA/V_project/final_2/repo
  d:/FPGA/V_project/IP/fft_reset1
  d:/FPGA/V_project/IP/PinRedistribution
  d:/FPGA/V_project/IP/reset
  d:/FPGA/V_project/IP/ad_fft
  d:/FPGA/V_project/IP/r_ram
  d:/FPGA/V_project/IP/pwm
  d:/FPGA/V_project/IP/w_ram
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files D:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_140M_1/system_rst_processing_system7_0_140M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_140M_1/system_rst_processing_system7_0_140M_1.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_140M_1/system_rst_processing_system7_0_140M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_2/system_rst_processing_system7_0_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_2/system_rst_processing_system7_0_100M_2.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_100M_2/system_rst_processing_system7_0_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_0/system_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_blk_mem_gen_0_1/system_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib D:/FPGA/V_project/final_2/lcd7_touch.srcs/sources_1/bd/system/hdl/system_wrapper.v
read_xdc D:/FPGA/V_project/final_2/lcd7_touch.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files D:/FPGA/V_project/final_2/lcd7_touch.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top system_wrapper -part xc7z020clg400-2
write_checkpoint -noxdef system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
